default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails7_ruby3_hotwire_todo_development
  username: <%=ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  #schema_search_path: myapp,sharedapp,public
  #min_messages: notice

test:
  <<: *default
  database: rails7_ruby3_hotwire_todo_test

production:
  <<: *default
  database: rails7_ruby3_hotwire_todo_production
  username: rails7_ruby3_hotwire_todo
  password: <%= ENV["RAILS7_RUBY3_HOTWIRE_TODO_DATABASE_PASSWORD"] %>
